# Generated by Django 4.2.1 on 2023-12-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_historicalperformance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperformance',
            name='history_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
